name: VillagerBlock
main: me.NetFire.TesCZ.VillagerBlock.main
author: TesCZ
version: 1.1
commands:
   vreload:
      description: Reload config of this plugin
permissions:
   villagerblock.cankill:
     description: can kill villager
   villagerblock.reload:
     description: reload config